max_text_length: 30
min_text_length: 8
sort_dataset: True
shuffle: True
logdir: ./log/
vocab_path: ./data/dict.p
non_lang_syms_path: ./data/non_lang_syms.p
dataset_root_dir: ./data
train_set: train
dev_set: val
test_set: test
batch_size: 64
ls_weight: 0.05
embedding_dim: 100
enc_hidden_dim: 160
enc_n_layers: 2
enc_dropout_p: 0.2
bidir_enc: True
pretrain_w2v_path: 
update_embedding: True
dec_hidden_dim: 160
dec_dropout_p: 0.2
use_attention: False
s_classifier_hidden_dim: 100
s_classifier_n_layers: 2
n_style_type: 2
learning_rate_m1: 0.0001
learning_rate_m2: 0.001
weight_decay_m1: 0.0000001
weight_decay_m2: 0.0000001
load_model_path: 
load_optimizer: True

