max_text_length: 15
min_text_length: 1
sort_dataset: True
shuffle: True
logdir: ./log/yelp/selfatt_mask/
vocab_path: ../data/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ../data/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ../style_word_alignment/self-attn-mask/masked_data/
train_pos: pos_train_selfattmask
train_neg: neg_train_selfattmask
dev_pos: pos_dev_selfattmask
dev_neg: neg_dev_selfattmask
test_pos: reference.1.selfattask
test_neg: reference.0.selfattmask
batch_size: 512
pretrain_w2v_path: ../pretrain_w2v/glove.6B.100d.w2vformat
embedding_dim: 100
update_embedding: True
enc_hidden_dim: 256
enc_n_layers: 3
enc_dropout_p: 0.2
bidirectional: True
dec_hidden_dim: 256
dec_dropout_p: 0.2
n_style_type: 2
style_emb_dim: 32
att_dim: 256
learning_rate: 0.0005
weight_decay: 0.0000001
load_model_path: 
load_optimizer: True
adjust_lr: False
retrieve_lr: 0.0005
epochs: 20
max_dec_timesteps: 15
max_grad_norm: 5
tag: delete_only
model_dir: ./models/yelp/selfatt_mask
model_name: deleat_only_selfatt
early_stop_start_epoch: 5
early_stop_patience: 3
dev_file_path: ./predictions/yelp/selfatt_mask/dev/
style_classifier_path: ../evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/selfatt_mask/test/
