logdir: ./log/yelp/selfatt_mask/rcnn_train_all_testing
vocab_path: ../../data/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ../../data/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ../self-attn-mask/masked_data
train_pos: pos_train_selfattmask
train_neg: neg_train_selfattmask
dev_pos: pos_dev_selfattmask
dev_neg: neg_dev_selfattmask
#test_pos: reference.1.selfattmask
#test_neg: reference.0.selfattmask
test_pos: pos_train_selfattmask
test_neg: neg_train_selfattmask
max_text_length: 15
min_text_length: 1
batch_size: 512
sort_dataset: True
pretrain_w2v_path: ../../pretrain_w2v/glove.6B.100d.w2vformat
embedding_dim: 100
rnn_hidden_dim: 128
linear_dim: 100
learning_rate: 0.001
weight_decay: 0.00000001
load_model_path: ./models/yelp/selfatt_mask/train_all/train_all_best
load_optimizer: False
retrieve_lr: 0.001
epochs: 10
max_grad_norm: 5
tag: yelp.selfatt_mask.train_all
model_dir: ./models/yelp/selfatt_mask/train_all
model_name: train_all
early_stop_start_epoch: 2
early_stop_patience: 3
train_target: all
test_target: remain
