max_text_length: 15
min_text_length: 1
sort_dataset: True
shuffle: True
logdir: ./log/yelp/style_proposed_att_adver/proposed_att_adver
vocab_path: ./data/preprocess/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ./data/preprocess/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ./data/preprocess/yelp/picklefiles
train_pos: pos_train
train_neg: neg_train
dev_pos: pos_dev
dev_neg: neg_dev
#test_pos: pos_test
#test_neg: neg_test
test_pos: reference.1
test_neg: reference.0
batch_size: 512
pretrain_w2v_path: 
embedding_dim: 256
encS_hidden_dim: 256
encC_hidden_dim: 512
encS_n_layers: 3
encC_n_layers: 3
enc_dropout_p: 0.1
bidir_enc: True
update_embedding: True
disen_c_hidden_dim: 256
disen_c_dnn_dim: 128
disen_s_hidden_dim: 256
mimicker_hidden_dim: [32,128,256]
#mimicker_hidden_dim: [32,64]
attention_dim: 512
domain_discri_dim: 256
ls_weight: 0.0
dec_hidden_dim: 512
dec_dropout_p: 0.1
n_style_type: 2
use_enc_init: False
style_cls_hidden: [256,256,512]
learning_rate_m0: 0.0005
learning_rate_m1: 0.0005
learning_rate_m2: 0.005
learning_rate_m3: 0.005
weight_decay_m0: 1e-7
weight_decay_m1: 1e-7
weight_decay_m2: 1e-7
weight_decay_m3: 1e-7
load_model_path: ./models/yelp/
load_optimizer: True
adjust_lr: False
retrieve_lr_m0: 0.0001
retrieve_lr_m1: 0.0001
retrieve_lr_m2: 0.002
retrieve_lr_m3: 0.0005
init_tf_rate: 1.0
tf_start_decay_epochs: 10
tf_decay_epochs: 20
tf_rate_lowerbound: 1.0
epochs: 20
m2_train_freq: 6
max_dec_timesteps: 20
max_grad_norm: 5
tag: style_proposed_att_adver
model_dir: ./models/yelp/style_att_adver
model_name: style_att_adver
early_stop_start_epoch: 7
early_stop_patience: 3
dev_file_path: ./predictions/yelp/attention_adver/dev/
style_classifier_path: ./evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/attention_adver/test_reference/
humanref_path_pos: ./data/preprocess/yelp/reference.1.humanout
humanref_path_neg: ./data/preprocess/yelp/reference.0.humanout
