max_text_length: 15
min_text_length: 1
sort_dataset: True
shuffle: True
logdir: ./log/yelp/style_transfer_proposed/proposed
vocab_path: ./data/preprocess/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ./data/preprocess/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ./data/preprocess/yelp/picklefiles
train_pos: pos_train
train_neg: neg_train
dev_pos: pos_dev
dev_neg: neg_dev
#test_pos: pos_test
#test_neg: neg_test
test_pos: reference.1
test_neg: reference.0
batch_size: 100
pretrain_w2v_path: 
embedding_dim: 256
encS_hidden_dim: 128
encC_hidden_dim: 256
encS_n_layers: 2
encC_n_layers: 2
enc_dropout_p: 0.1
bidir_enc: True
update_embedding: True
disen_s_hidden_dim: [256,256,512]
disen_c_hidden_dim: [512,256,256]
mimicker_hidden_dim: [512,256]
domain_discri_dim: 128
ls_weight: 0.0
dec_hidden_dim: 256
dec_dropout_p: 0.1
n_style_type: 2
use_enc_init: True
style_cls_hidden: [256,128,64]
learning_rate_m1: 0.0001
learning_rate_m2: 0.001
learning_rate_m3: 0.0005
weight_decay_m1: 1e-7
weight_decay_m2: 1e-7
weight_decay_m3: 1e-7
load_model_path: ./models/yelp/style_proposed/style_proposed_latest 
load_optimizer: True
adjust_lr: False
retrieve_lr_m1: 0.0001
retrieve_lr_m2: 0.001
retrieve_lr_m3: 0.0005
init_tf_rate: 1.0
tf_start_decay_epochs: 10
tf_decay_epochs: 20
tf_rate_lowerbound: 1.0
epochs: 18
m2_train_freq: 4
max_dec_timesteps: 20
max_grad_norm: 5
tag: style_transfer_proposed
model_dir: ./models/yelp/style_proposed
model_name: style_proposed
early_stop_start_epoch: 5
early_stop_patience: 3
dev_file_path: ./predictions/yelp/proposed/dev/
style_classifier_path: ./evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/proposed/test_reference/
humanref_path_pos: ./data/preprocess/yelp/reference.1.humanout
humanref_path_neg: ./data/preprocess/yelp/reference.0.humanout
