max_text_length: 15
min_text_length: 1
sort_dataset: True
shuffle: True
logdir: ./log/yelp/pretrain_classifier
vocab_path: ./data/preprocess/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ./data/preprocess/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ./data/preprocess/yelp/picklefiles
train_pos: pos_train
train_neg: neg_train
dev_pos: pos_dev
dev_neg: neg_dev
#test_pos: pos_test
#test_neg: neg_test
test_pos: reference.1
test_neg: reference.0
batch_size: 32
pretrain_w2v_path: ./pretrain_w2v/glove.6B.100d.w2vformat
embedding_dim: 100
rnn_hidden_dim: 256
dropout_p: 0.1
dnn_hidden_dim: 256
att_dim: 256
update_embedding: True
learning_rate: 0.001
weight_decay: 0.000001
load_model_path: ./models/yelp/
load_optimizer: True
adjust_lr: False
retrieve_lr: 5e-4
epochs: 8
max_grad_norm: 5
tag: yelp.pretrain_classifier
model_dir: ./models/yelp/pretrain_classifier_new
model_name: pretrain_classifier
early_stop_start_epoch: 2
early_stop_patience: 2
dev_file_path: ./predictions/yelp/pretrain_classifier_new/dev/
test_file_path: ./predictions/yelp/pretrain_classifier_new/test_reference/
