max_text_length: 30
min_text_length: 8
sort_dataset: True
shuffle: True
logdir: ./log/style_transfer_cycle/
vocab_path: ./data/dict.p
non_lang_syms_path: ./data/non_lang_syms.p
dataset_root_dir: ./data
train_set: train
pos_train_set: pos_train
neg_train_set: neg_train
dev_set: val
pos_dev_set: pos_val
neg_dev_set: neg_val
test_set: test
batch_size: 220
ls_weight: 0.0
embedding_dim: 100
enc_hidden_dim: 256
enc_n_layers: 3
enc_dropout_p: 0.2
bidir_enc: True
pretrain_w2v_path: 
update_embedding: True
dec_hidden_dim: 256
dec_dropout_p: 0.1
use_attention: False
use_enc_init: True
s_classifier_hidden_dim: 128
s_classifier_n_layers: 3
n_style_type: 2
style_emb_dim: 16
discri_hidden_dim: 128
discri_dropout_p: 0.2
learning_rate_m1: 0.001
learning_rate_m2: 0.002
learning_rate_m3: 0.001
weight_decay_m1: 0.0000001
weight_decay_m2: 0.0000001
weight_decay_m3: 0.0000001
load_model_path: 
load_optimizer: True
adjust_lr: False
retrieve_lr_m1: 0.002
retrieve_lr_m2: 0.004
retrieve_lr_m3: 0.002
init_tf_rate: 1.0
tf_start_decay_epochs: 5
tf_decay_epochs: 35
tf_rate_lowerbound: 0.7
change_lr_epoch: 30,40
lr_gamma: 0.5
epochs: 50
max_dec_timesteps: 30
recons_loss_ratio: 2
style_loss_ratio: 1
cycle_loss_ratio: 1
discri_loss_ratio: 1
max_grad_norm: 5
tag: style_transfer_cycle
m2_train_freq: 5
sample_num: 10
model_dir: ./models/style_transfer_cycle/
model_name: style_transfer_cycle
early_stop_start_epoch: 20
early_stop_patience: 15
test_file_name: ./tests/test_cycle
