#max_text_length: 30
max_text_length: 20
min_text_length: 8
sort_dataset: True
shuffle: True
logdir: ./log/proposed_framework_test/proposed_framework_test
vocab_path: ./data/dict.p
non_lang_syms_path: ./data/non_lang_syms.p
dataset_root_dir: ./data
train_set: train
pos_train_set: pos_train
neg_train_set: neg_train
dev_set: val
test_set: test
batch_size: 96
ls_weight: 0.0
embedding_dim: 100
encS_hidden_dim: 200
encC_hidden_dim: 200
encS_n_layers: 2
encC_n_layers: 2
enc_dropout_p: 0.2
bidir_enc: True
pretrain_w2v_path: 
update_embedding: True
disen_s_hidden_dim: [128,64]
disen_c_hidden_dim: [128,64]
mimicker_hidden_dim: [128,64]
dec_hidden_dim: 250
dec_dropout_p: 0.1
use_attention: False
use_enc_init: True
s_classifier_hidden_dim: 120
s_classifier_n_layers: 3
n_style_type: 2
style_emb_dim: 16
learning_rate_m1: 0.0005
learning_rate_m2: 0.002
weight_decay_m1: 0.0000001
weight_decay_m2: 0.0000001
load_model_path: ./models/style_transfer_proposed/style_transfer_proposed_latest
load_optimizer: True
load_pretrained_style_classifier_path: ./models/pretrained_cnn_style_classifier/pretrained_style_classifier_best
train_pretrained_style_classifier: False
adjust_lr: False
retrieve_lr_m1: 0.002
retrieve_lr_m2: 0.004
init_tf_rate: 1.0
tf_start_decay_epochs: 3
tf_decay_epochs: 10
tf_rate_lowerbound: 0.7
change_lr_epoch: 8
lr_gamma: 0.5
epochs: 12
#max_dec_timesteps: 30
max_dec_timesteps: 20
max_grad_norm: 5
tag: style_transfer_proposed
m2_train_freq: 5
sample_num: 10
model_dir: ./models/style_transfer_proposed
model_name: style_transfer_proposed
early_stop_start_epoch: 10
early_stop_patience: 5
test_file_name: ./tests/proposed
