max_text_length: 15
min_text_length: 3
sort_dataset: True
shuffle: True
logdir: ./log/yelp/cycle_ourstan_nocover_denoise
vocab_path: ./cycle_data/ori_data/vocab_dict.p
non_lang_syms_path: ./cycle_data/ori_data/non_lang_syms.p
dataset_root_dir: ./cycle_data/data/
train_pos: neg_train
train_neg: pos_train
dev_pos: pos_test
dev_neg: neg_test
test_pos: pos_test
test_neg: neg_test
batch_size: 512
#pretrain_w2v_path: ./pretrain_w2v/glove.6B.100d.w2vformat
pretrain_w2v_path: 
embedding_dim: 100
enc_hidden_dim: 256
enc_n_layers: 3
enc_dropout_p: 0.2
bidir_enc: True
update_embedding: True
dec_hidden_dim: 256
dec_dropout_p: 0.2
n_style_type: 2
style_emb_dim: 32
att_dim: 256
learning_rate: 0.001
weight_decay: 1e-7
load_model_path: ./models/yelp/
load_optimizer: True
adjust_lr: False
retrieve_lr: 0.0005
init_tf_rate: 1.0
tf_start_decay_epochs: 3
tf_decay_epochs: 5
tf_rate_lowerbound: 0.9
epochs: 15
max_dec_timesteps: 15
max_grad_norm: 5
tag: cycle
model_dir: ./models/yelp/cycle_ourstan_nocover_denoise
model_name: cycle
early_stop_start_epoch: 4
early_stop_patience: 2
dev_file_path: ./predictions/yelp/cycle_ourstan_nocover_denoise/dev/
style_classifier_path: ./evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/cycle_ourstan_nocover_denoise/test/
humanref_path_pos: ../data/preprocess/yelp/reference.1.humanout
humanref_path_neg: ../data/preprocess/yelp/reference.0.humanout
