max_text_length: 15
min_text_length: 1
sort_dataset: True
shuffle: True
logdir: ./log/yelp/dynamic_mask_nopretrain/
vocab_path: ../data/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ../data/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ../data/yelp/picklefiles/
train_pos: pos_train
train_neg: neg_train
dev_pos: pos_dev
dev_neg: neg_dev
test_pos: reference.1
test_neg: reference.0
batch_size: 512
pretrain_w2v_path: ../pretrain_w2v/glove.6B.100d.w2vformat
embedding_dim: 100
update_embedding: True
enc_hidden_dim: 256
enc_n_layers: 3
enc_dropout_p: 0.2
bidirectional: True
maskgen_dim: 128
dec_hidden_dim: 256
dec_dropout_p: 0.2
n_style_type: 2
style_emb_dim: 32
att_dim: 256
cls_dim: 256
learning_rate: 0.0005
weight_decay: 0.0000001
load_model_path: ./models/yelp/dynamic_mask_pretrain/dynamic_mask_pretrain-06_b1.0g1.0 
load_optimizer: False
adjust_lr: False
retrieve_lr: 0.0005
epochs: 15
max_dec_timesteps: 15
max_grad_norm: 5
tag: dynamic_mask
model_dir: ./models/yelp/dynamic_mask_nopretrain
model_name: dynamic_mask
early_stop_start_epoch: 2
early_stop_patience: 3
dev_file_path: ./predictions/yelp/dev/dynamic_mask_nopretrain_
style_classifier_path: ../evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/test/dynamic_mask_nopretrain_
detach_recons: False
