max_text_length: 15
min_text_length: 3
sort_dataset: True
shuffle: True
logdir: ./log/yelp/cyclemodel_stanfordmask_denoise_nomask_wcycle
vocab_path: ./data/preprocess/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ./data/preprocess/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ./emotion_word_detector/stanford_mask/yelp
train_pos: pos_train_withA_stanford
train_neg: neg_train_withA_stanford
dev_pos: pos_test_withA_stanford
dev_neg: neg_test_withA_stanford
test_pos: pos_test_withA_stanford
test_neg: neg_test_withA_stanford
batch_size: 512
#pretrain_w2v_path: ./pretrain_w2v/glove.6B.100d.w2vformat
pretrain_w2v_path: 
embedding_dim: 300
enc_hidden_dim: 256
enc_n_layers: 3
enc_dropout_p: 0.2
bidir_enc: True
update_embedding: True
dec_hidden_dim: 256
dec_dropout_p: 0.2
n_style_type: 2
style_emb_dim: 32
att_dim: 256
learning_rate: 0.0005
weight_decay: 1e-7
load_model_path: ./models/yelp/
load_optimizer: True
adjust_lr: False
retrieve_lr: 0.0005
init_tf_rate: 1.0
tf_start_decay_epochs: 4
tf_decay_epochs: 10
tf_rate_lowerbound: 0.9
epochs: 20
max_dec_timesteps: 17
max_grad_norm: 5
tag: cycle_model
model_dir: ./models/yelp/cycle_model_stanfordmask_denoise_nomask_wcycle
model_name: cycle_model
early_stop_start_epoch: 7
early_stop_patience: 3
dev_file_path: ./predictions/yelp/cycle_stanfordmask_denoise_nomask_wcycle/dev/
style_classifier_path: ./evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/cycle_stanfordmask_denoise_nomask_wcycel/test/
humanref_path_pos: ./data/preprocess/yelp/reference.1.humanout
humanref_path_neg: ./data/preprocess/yelp/reference.0.humanout
