max_text_length: 15
min_text_length: 1
sort_dataset: True
shuffle: True
logdir: ./log/yelp/base_dynamic_gumbel/base_
vocab_path: ./data/preprocess/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ./data/preprocess/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ./emotion_word_detector/alignment_data/yelp
train_pos: pos_train_withA
train_neg: neg_train_withA
dev_pos: pos_dev_withA
dev_neg: neg_dev_withA
test_pos: pos_test_withA
test_neg: neg_test_withA
batch_size: 256
#pretrain_w2v_path: ./pretrain_w2v/glove.6B.100d.w2vformat
pretrain_w2v_path: 
embedding_dim: 100
update_embedding: True
enc_hidden_dim: 256
enc_n_layers: 3
enc_dropout_p: 0.2
bidirectional: True
maskgen_dim: 128
dec_hidden_dim: 256
dec_dropout_p: 0.2
n_style_type: 2
style_emb_dim: 32
att_dim: 256
cls_dim: 256
cls_dropout_p: 0.2
cls_att_dim: 128
learning_rate: 0.0005
weight_decay: 1e-7
load_model_path: ./models/yelp/base_dynamic/
load_optimizer: True
adjust_lr: False
retrieve_lr: 0.0005
init_tf_rate: 1.0
tf_start_decay_epochs: 2
tf_decay_epochs: 4
tf_rate_lowerbound: 0.90
epochs: 15
max_dec_timesteps: 15
max_grad_norm: 5
tag: base_dynamic
model_dir: ./models/yelp/base_dynamic_gumbel
model_name: base_dynamic
early_stop_start_epoch: 2
early_stop_patience: 3
dev_file_path: ./predictions/yelp/base_dynamic_gumbel/dev
style_classifier_path: ./evaluation/transfer_ability/yelp/model_yelp.bin
test_file_path: ./predictions/yelp/base_dynamic_gumbel/test
humanref_path_pos: ./data/preprocess/yelp/reference.1.humanout
humanref_path_neg: ./data/preprocess/yelp/reference.0.humanout
