logdir: ./log/yelp/stanford_mask/rcnn_train_mask
vocab_path: ../../data/yelp/picklefiles/vocab_dict.p
non_lang_syms_path: ../../data/yelp/picklefiles/non_lang_syms.p
dataset_root_dir: ../stanford-mask/yelp_stanford/data
train_pos: pos_train_stanfordmask
train_neg: neg_train_stanfordmask
dev_pos: pos_dev_stanfordmask
dev_neg: neg_dev_stanfordmask
test_pos: reference.1.stanfordmask
test_neg: reference.0.stanfordmask
max_text_length: 15
min_text_length: 1
batch_size: 512
sort_dataset: True
pretrain_w2v_path: ../../pretrain_w2v/glove.6B.100d.w2vformat
embedding_dim: 100
rnn_hidden_dim: 128
linear_dim: 100
learning_rate: 0.001
weight_decay: 0.00000001
load_model_path:
load_optimizer: False
retrieve_lr: 0.001
epochs: 10
max_grad_norm: 5
tag: yelp.stanford_mask.train_mask
model_dir: ./models/yelp/stanford_mask/train_mask
model_name: train_mask
early_stop_start_epoch: 2
early_stop_patience: 3
train_target: mask
test_target: mask
